language: python
python:
  - "3.7"
cache: pip
install:
  - pip install -r requirements.txt
env:
  -
script:
  - python Marko_Ventures/manage.py test core
  - coverage run --source='Marko_Ventures/core' Marko_Ventures/manage.py test core
  - coverage report
after_success:
  - coveralls